fix(wildcards): remove old secret references
davidmarkclements/fast-redact pull request #67
Opened 2024-03-07 04:42 UTC by roggervalf

fixes https://github.com/davidmarkclements/fast-redact/issues/63
in next call, we can remove old wildcard references from secret object to prevent memory leak

2024-03-07 04:44 UTC, roggervalf commented
pls @mcollina when you get some time

2024-03-07 11:18 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test?

2024-03-07 14:13 UTC, roggervalf commented on lib/redactor.js
> +  redact.secret = secret
this is only for test case to compare the size of it

2024-03-07 14:14 UTC, roggervalf commented
@mcollina test was added, pls when you get some time

2024-03-07 16:39 UTC, mcollina approved these changes
lgtm

2024-03-07 17:29 UTC, merged

2024-03-12 12:41 UTC, msala-fp commented
@mcollina These changes are breaking. If you will use more then once the same redact instance, it fails to restore the second object. It is breaking "pino" logger at our side. I can't be sure the source of the problem is the same, but if yes, so it could have bigger impact for lot of users.
Just try this test:
```
test('restores multi nested wildcard values, twice', ({ end, is }) => {
  const o = {
    a: {
      b1: {
        c1: {
          d1: { e: '123' },
          d2: { e: '456' }
        },
        c2: {
          d1: { e: '789' },
          d2: { e: '012' }
        }
      },
      b2: {
        c1: {
          d1: { e: '345' },
          d2: { e: '678' }
        },
        c2: {
          d1: { e: '901' },
          d2: { e: '234' }
        }
      }
    }
  }
  const o2 = {
    a: {
      b1: {
        c1: {
          d1: { e: '123' },
          d2: { e: '456' }
        },
        c2: {
          d1: { e: '789' },
          d2: { e: '012' }
        }
      },
      b2: {
        c1: {
          d1: { e: '345' },
          d2: { e: '678' }
        },
        c2: {
          d1: { e: '901' },
          d2: { e: '234' }
        }
      }
    }
  }

  const censor = 'censor'
  const paths = ['a.*.*.*.e']
  const redact = fastRedact({ paths, censor, serialize: false })

  redact(o)
  is(o.a.b1.c1.d1.e, censor)
  is(o.a.b1.c1.d2.e, censor)
  is(o.a.b1.c2.d1.e, censor)
  is(o.a.b1.c2.d2.e, censor)
  is(o.a.b2.c1.d1.e, censor)
  is(o.a.b2.c1.d2.e, censor)
  is(o.a.b2.c2.d1.e, censor)
  is(o.a.b2.c2.d2.e, censor)
  redact.restore(o)
  is(o.a.b1.c1.d1.e, '123')
  is(o.a.b1.c1.d2.e, '456')
  is(o.a.b1.c2.d1.e, '789')
  is(o.a.b1.c2.d2.e, '012')
  is(o.a.b2.c1.d1.e, '345')
  is(o.a.b2.c1.d2.e, '678')
  is(o.a.b2.c2.d1.e, '901')
  is(o.a.b2.c2.d2.e, '234')

  redact(o2)
  is(o2.a.b1.c1.d1.e, censor)
  is(o2.a.b1.c1.d2.e, censor)
  is(o2.a.b1.c2.d1.e, censor)
  is(o2.a.b1.c2.d2.e, censor)
  is(o2.a.b2.c1.d1.e, censor)
  is(o2.a.b2.c1.d2.e, censor)
  is(o2.a.b2.c2.d1.e, censor)
  is(o2.a.b2.c2.d2.e, censor)
  redact.restore(o2)
  is(o2.a.b1.c1.d1.e, '123')
  is(o2.a.b1.c1.d2.e, '456')
  is(o2.a.b1.c2.d1.e, '789')
  is(o2.a.b1.c2.d2.e, '012')
  is(o2.a.b2.c1.d1.e, '345')
  is(o2.a.b2.c1.d2.e, '678')
  is(o2.a.b2.c2.d1.e, '901')
  is(o2.a.b2.c2.d2.e, '234')

  end()
})
```

2024-03-13 06:35 UTC, tadhglewis commented
We also ran into this issue which can cause pretty major data issues depending on your usage of pino/fast-redact 😬

2024-03-13 06:47 UTC, 72636c commented
Here's a minimal-ish repro for the pino logging use case:

```typescript
import { pino } from 'pino';

const logger = pino({ redact: { censor: '???', paths: ['props.*'] } });

const props = { name: 'PII' };

logger.child({ props });
logger.child({ props });

console.log({ props });
// { props: { name: '???' } }
```

2024-03-13 11:47 UTC, MSala commented
I have prepared a PR with potential fixes, retaining the benefits of changes from this PR.
See: https://github.com/davidmarkclements/fast-redact/pull/69
CC: @mcollina @roggervalf